### ISSUE TITLE
@thx/money throws an error

### ISSUE THREAD

**Issue by hjp2412** [thr-consulting/thr-addons#10]
I have imported "makeMoney" from @thx/money inside "thr4/tools/remoteServices/api/subsistence.js", and now on server side I am getting following error:

/home/himanshi/dev/thr4/node_modules/inputmask/dist/inputmask/global/window.js:11
}) : "object" == typeof exports && (module.exports = window);
                                                     ^
ReferenceError: window is not defined
    at Object.<anonymous> (/home/himanshi/dev/thr4/node_modules/inputmask/dist/inputmask/global/window.js:11:54)

**Comment by darkadept** [comment]
I'm going to need more details then this.

What API method are you calling? What is your import code?

**Comment by darkadept** [comment]
You need to show your import statement.

I assume you're importing it like this: `import {makeMoney} from '@thx/money';`.
This would be incorrect for server-side code.

You need to import from the server index `import {makeMoney} from '@thx/money/server';`.
