### ISSUE TITLE
Allow tabbing from a date control when entering the date via the text input.

### ISSUE THREAD

**Issue by darkadept** [thr-consulting/thr-addons#305]

**Comment by JohnnySpomer** [comment]
looking at the react-datepicker source code: https://github.com/Hacker0x01/react-datepicker/blob/master/src/index.jsx
- the PopperComponent has a prop called popperOnKeyDown that is set internally and not exposed, so using that to manipulate the tab is not possible. the only thing it reacts to currently is the escape button.

adding a tab index of -1 to the DatePicker skips the component entirely
